#pragma once

enum class UGVNavState {WARMINGUP, IDLE, UTILITY, HEADINGTOWARDSENTRANCE, SEARCHINGFORFIRE, HEADINGTOWARDSFIRE, 
                        UGVALIGNINGWITHTARGET, UGVALIGNEDWITHTARGET, EXTINGUISHINGFIRE, RETURNINGTOBASE, REACHEDBASE};